os: linux
dist: xenial
language: ruby
services:
    - docker
before_install:
    - docker build -t js/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true js/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket: "elasticbeanstalk-us-east-1-675489459153"
    path: "docker-react"
    on:
        branch: "master"
    access_key_id: $access_key
    secret_access_key: $secret_key
